spring.application.name=playvee

spring.datasource.url=jdbc:postgresql://localhost:5434/playvee
spring.datasource.username=playvee
spring.datasource.password=playvee
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true